import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistery from "../../theme/ThemeRegistery.js";
import { ReduxProvider } from "./redux/ReduxProvider";
import { Box, Container, Grid, Typography } from "@mui/material";
import MainNavigation from "./components/MainNavigation/MainNavigation";
import Footer from "./components/Footer/Footer";
import BusinessLogo from "./components/BusinessLogo/BusinessLogo";
import "./globalStyles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistery options={{ key: "mui-theme" }}>
        <ReduxProvider>
          <body>
            <Grid container spacing={0.5}>
              <Grid item md={12}>
                <Container>
                  <BusinessLogo />
                </Container>
              </Grid>
              <Grid item md={12}>
                <MainNavigation />
              </Grid>
              <Grid item md={12}>
                <Box>{children}</Box>
              </Grid>
              <Grid item md={12}>
                <Footer />
              </Grid>
            </Grid>
          </body>
        </ReduxProvider>
      </ThemeRegistery>
    </html>
  );
}
