import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import ThemeRegistery from "../../theme/ThemeRegistery.js";
import { ReduxProvider } from "./redux/ReduxProvider";
import { Box, Container, Grid, Typography } from "@mui/material";
import MainNavigation from "./components/MainNavigation/MainNavigation";
import Footer from "./components/Footer/Footer";
import BusinessLogo from "./components/BusinessLogo/BusinessLogo";
import "./globalStyles.css";
import MainNavigationV2 from "./components/MainNavigationV2/MainNavigationV2";
import CategoriesCardSection from "./components/CategoriesCardSection/CategoriesCardSection";
import FooterV2 from "./components/Footer/FooterV2";
import MainNavigationV3 from "./components/MainNavigationV3/MainNavigationV3";
import SectionHeading from "./components/SectionHeading/SectionHeading";
import FooterV3 from "./components/Footer/FooterV3";

const NunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;500;600;700;800;900&display=swap"
        />
      </head>
      <ThemeRegistery options={{ key: "mui-theme" }}>
        <ReduxProvider>
          <body className={NunitoSans.className}>
            <MainNavigationV3 />
            <Box>{children}</Box>
            <Grid container mt={5} md={12}>
              <Container>
                <Box my={10}>
                  <SectionHeading text={"Explore More at Adventurr.tech"} />
                </Box>
                <CategoriesCardSection />
              </Container>
            </Grid>
            <Grid mt={10} item md={12} sx={{ backgroundColor: "#e4e4e6" }}>
              <FooterV3 />
            </Grid>
          </body>
        </ReduxProvider>
      </ThemeRegistery>
    </html>
  );
}
